version: 2
jobs:
  test:
    - image: circleci/python:3.6.5
    steps:
      - checkout
      -run:
        name: pytest
        command: |
          pytest
  deploy:
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - run:
          name: heroku deploy
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_PROD.git master
workflows:
  version: 2
  deploy:
    jobs:
      - test:
      - deploy:
          reqires:
            - test
          filters:
            branches:
              only: master